DEFAULT_GROUP_SETTINGS = {
    "general": {
        "title_generation_prompt": "", # Empty, because if empty, it uses the default one.
    },
    "chat": {
        "show_chat_box_warning": False,
        "chat_box_warning_message": "AI can make mistakes. Double check information.",
        "allow_temporary_chat": True,
        "allow_regenerate_response": True,
        "allow_rate_response": True,
        "allow_delete_messages": True,
        "auto_delete_chats": False,
        "auto_delete_chats_days": 30,
        "allow_chat_deletion": True,
        "shadow_chat_deletion": False,
        "shadow_chat_deletion_retention_enabled": True,
        "shadow_chat_deletion_retention_days": 30,
        "save_temp_chats": False,
        "save_temp_chats_retention_enabled": True,
        "save_temp_chats_retention_days": 30,
        "allow_byok": True,
        "byok_allowed_tools": [],
        "byok_title_generation_model_id": "",
        "byok_default_scrape_provider": "",
        "byok_default_search_provider": "",
    },
    "users": {
        "enable_custom_profile_picture": True,
        "allow_change_name": True, 
        "allow_change_email": True,
        "allow_change_password": True, # Only for changing in the user settings screen, "has_to_change_password" is still allowed/forced
        "allow_self_deletion": True,
    },
    "context": {
        "enable_group_context": False,
        "group_context": "",
        "group_context_file_ids": [],
    },
    "projects": {
        "enable_projects": True,
        "allow_project_share": True,
    },
    "files": {
        "allow_file_uploads": True,
        "max_files_upload_count": 100,
        "max_user_files_size_gb": 5,
    },
    "todo": {
        "enabled_todo": True,
        "allow_todo_list_share": True
    },
    "notes": {
        "enabled_notes": True,
        "allow_notes_share": True
    },
    "memories": {
        "enabled_memories": True,
        # Empty means the model used for the current chat turn. Administrators
        # can choose a dedicated inexpensive completion model per group.
        "memory_model_id": "",
    },
    "skills": {
        "enabled_skills": True,
        "allow_skill_share": True,
        "admin_skill_ids": [],
    },
    "prompts": {
        "enabled_prompts": True,
        "allow_prompt_share": True,
    },
    "bookmarks": {
        "enabled_bookmarks": True,
        "allow_bookmark_share": True,
    },
    "agents": {
        "allow_agents": True,
        "allow_agent_share": True,
    },
    "automations": {
        "enabled_automations": True,
    },
    "leaderboard": {
        "enabled": False,
        "artificial_analysis_data_level": "free",
        "artificial_analysis_api_key": "",
    },
    "compliance": {
        "enable_content_credentials": False,
        "enable_watermark": False,
        "watermark": "This text is generated by artificial intelligence."
    },
    "data_controls": {
        "allow_user_data": True,
    },
    "access_windows": {
        "enabled": False,
        "timezone": "UTC",
        "mode": "allowlist",  # "allowlist" = only allow during rules, "blocklist" = block during rules
        "rules": [],  # List of {"start": "HH:MM", "end": "HH:MM", "days": [0-6], "label": "string"}
        "show_next_available": True,  # Show countdown to next available window
        "blocked_message": "",  # Custom message shown when access is blocked
    },
    "temporary_accounts": {
        "enabled": False,
        "max_active_accounts": 50,
        "credential_length": 24,
    },

    # Cross-surface sharing permissions shown in the admin and delegated
    # manager settings. Each group owns these values independently.
    "sharing": {
        "enable_chat_sharing": True,
        "enable_artifact_sharing": True,
    },
    "tools_mcp": {
        "enable_mcp": True,
        "allow_file_storage_connections": True,
        "enabled_connections": [],
    },
}
