DEFAULT_USER_SETTINGS = {
    "security": {
        "has_to_change_password": False,
        "profile_visibility": "private",  # public, private,
        "allow_llm_to_access_personal_information_preset": "none",  # none, all, custom
        "allow_llm_to_access_personal_information": {
            "first_name": False,
            "language": False,
            "country": False,
            "timezone": False,
            "location": False,
        },
    },
    "general": {
        "language": "",  # Langauge of the user, ISO 639-1
        "country": "",  # Country of the user, ISO 3166-1 alpha-2
        "timezone": "",
        "location": "",  # City or location of the user (free-form string)
    },
    "appearance": {
        "theme": "system",  # system, light, dark
        # Persisted message-bubble color; it does not recolor application UI.
        "color_theme": "mono",  # blue, green, coral, purple, teal, amber, mono
        "font": "inter",
    },
    "chat": {
        "last_model": "",  # Model id
        "speech_playback_speed": 1.0,
        "personality_preset": "none",
        "personality_custom_instruction": "",
        "render_user_messages_markdown": True,
        "render_assistant_messages_markdown": True,
        "ctrl_enter_to_send": False,
        "always_use_temporary_chat": False,
        "chat_full_width": False,
        "show_message_nav": True,
        "show_model_settings": False,
        "show_assistant_message_metadata": False,
        "pinned_models": [],
        "pinned_models_customized": False,
        "byok_statistics_enabled": False,
        "byok_statistics_retention_days": 90,
        # Sidebar button visibility
        "sidebar_button_visibility": {
            "create_chat": True,
            "search_chats": True,
            "workspace": True,
            "automations": True,
            "projects": True,
        },
    },
    "memory": {
        "enabled": True,
        "include_in_context": True,
        "auto_create": True,
    },
    "login_2fa": {
        "enable_2fa": False,
        "provider": "",
    },
    "secret": {
        "2fa_secret": "",
        "2fa_secret_pending": "",
        "2fa_otp_hash": "",
        "2fa_otp_expires_at": "",
        "2fa_otp_last_sent_at": "",
        "2fa_otp_attempts": 0,
        "2fa_otp_purpose": "",
        "2fa_otp_provider": "",
        "2fa_otp_destination": "",
        "2fa_totp_attempts": 0,
        "2fa_totp_locked_until": "",
        "2fa_totp_ip_hash": "",
        "2fa_totp_ip_attempts": 0,
        "2fa_totp_ip_locked_until": "",
        "passkey_pending_token": "",
        "passkey_pending_token_expires_at": "",
        "passkey_pending_setup_material_allowed": False,
        "signin_pending_token": "",
        "signin_pending_token_expires_at": "",
        "signin_pending_setup_material_allowed": False,
        "wrong_sign_in_attempts": 0,
    },
    "states": {
        "welcome_card_dismissed": False,
        "has_new_notifications": False,
        "privacy_policy_last_interacted_revision": None,
        "privacy_policy_accepted": False,
        "terms_of_service_accepted_revision": None,
        "terms_of_service_accepted_at": "",
    },
    "social_login": {
        "needs_password_setup": False,
        "google_linked": False,
        "google_user_id": "",
        "github_linked": False,
        "github_user_id": "",
        "slack_linked": False,
        "slack_user_id": "",
        "microsoft_linked": False,
        "microsoft_user_id": "",
        "apple_linked": False,
        "apple_user_id": "",
        "oauth_profile_picture_present": False,
        "oauth_profile_picture_provider": "",
        "oauth_profile_picture_last_synced_at": "",
        "oauth_profile_picture_sync_disabled": False,
        "pending_social_token": "",
        "pending_social_token_expires": "",
        "pending_provider": "",
        "pending_setup_material_allowed": False,
        "pending_auth_code": "",
        "pending_auth_code_expires": "",
    },
    "sso_login": {
        "needs_password_setup": False,
        "saml_linked": False,
        "saml_user_id": "",
        "oidc_linked": False,
        "oidc_user_id": "",
        "provider_id": "",
        "pending_sso_token": "",
        "pending_sso_token_expires": "",
        "pending_provider_type": "",
        "pending_setup_material_allowed": False,
        "pending_auth_code": "",
        "pending_auth_code_expires": "",
    },
    "scim": {
        "external_id": "",
        "last_synced_at": "",
    },
    "ldap_login": {
        "linked": False,
        "directory_user_id": "",
        "directory_dn": "",
        "directory_username": "",
        "last_login_identifier": "",
        "last_synced_at": "",
        "last_synced_groups": [],
    },
}
