"""Hardcoded upload limits for user-managed images."""

BYTES_PER_MIB = 1024 * 1024

CUSTOM_PROFILE_PICTURE_MAX_SIZE_MB = 5
CUSTOM_PROFILE_PICTURE_MAX_BYTES = CUSTOM_PROFILE_PICTURE_MAX_SIZE_MB * BYTES_PER_MIB
