from app.utils.privacy_policy_template import PRIVACY_POLICY_TEMPLATE
from app.utils.terms_of_service_template import TERMS_OF_SERVICE_TEMPLATE

DEFAULT_SETTINGS = {
    "general": {
        "public_url": [],
        "internet_connectivity_check_enabled": True,
        "offline_mode": False,
        "external_requests_mode": "allow_all",
        "external_requests_allowlist": [],
        "application_name": "Omlorix",
    },
    "login_general": {
        "enable_signin": True,
        "enable_signup": True,
        "enable_password_reset": False,
        "enable_2fa": True,
        "force_2fa": False,
        "twofa_provider": "totp",
        "otp_length": 6,
        "otp_ttl_seconds": 300,
        "otp_resend_cooldown_seconds": 30,
        "otp_max_attempts": 5,
        "email_from_address": "",
        "smtp_host": "",
        "smtp_port": 587,
        "smtp_username": "",
        "smtp_password": "",
        "smtp_use_tls": True,
        "smtp_use_ssl": False,
        "enable_passkeys": True,
        "specific_signup_domain": [],
        "contact_support_email": "",
        "default_user_role": "pending",
        "default_user_group": "default",
        "minimum_password_length": 10,
        "minimum_special_characters": 1,
        "minimum_uppercase_characters": 1,
        "minimum_lowercase_characters": 1,
        "minimum_number_characters": 1,
        "show_privacy_notice_link": False,
        "show_terms_of_service_link": False,
        "enforce_terms_of_service_signup_acceptance": False,
        "enforce_terms_of_service_access_acceptance": False,
    },
    "login_customization": {
        "show_custom_logo": False,
        "custom_logo_height": "medium",
        "login_design": "classic",
        "show_background_image": False,
        "background_image_fit": "cover",
        "background_image_size_percent": 100,
        "background_overlay_opacity": 40,
        "design_background_color": "#ffffff",
        "branding_title": "Welcome back",
        "branding_subtitle": "Sign in to continue to your account",
        "show_branding_text": True,
    },
    "login_social": {
        # Google OAuth
        "enable_google_oauth": False,
        "enable_google_login": False,
        "import_google_oauth_profile_picture": False,
        "google_client_id": "",
        "google_client_secret": "",
        # Google Picker runs in the browser and therefore needs the project's
        # referrer-restricted browser key and numeric Google Cloud project id.
        "google_picker_api_key": "",
        "google_picker_app_id": "",
        "google_button_text": "",
        "google_allowed_domains": [],
        "google_allow_signup": True,
        # GitHub OAuth
        "enable_github_oauth": False,
        "enable_github_login": False,
        "import_github_oauth_profile_picture": False,
        "github_base_url": "https://github.com",
        "github_client_id": "",
        "github_client_secret": "",
        "github_connection_scope_tier": "repository_access",
        "github_button_text": "",
        "github_allowed_domains": [],
        "github_allowed_organizations": [],
        "github_allow_signup": True,
        # Slack OAuth
        "enable_slack_oauth": False,
        "enable_slack_login": False,
        "import_slack_oauth_profile_picture": False,
        "slack_client_id": "",
        "slack_client_secret": "",
        "slack_connection_scope_tier": "public_read",
        # Empty preserves the translated built-in label on the login page.
        "slack_button_text": "",
        "slack_allowed_domains": [],
        "slack_allowed_workspace_ids": [],
        "slack_allow_signup": True,
        # Microsoft OAuth
        "enable_microsoft_oauth": False,
        "enable_microsoft_login": False,
        # Choose account types explicitly for the Azure app registration.
        # Single-tenant deployments should replace ``common`` with their
        # tenant GUID or verified tenant domain.
        "microsoft_tenant": "common",
        "microsoft_client_id": "",
        "microsoft_client_secret": "",
        "import_microsoft_oauth_profile_picture": False,
        "microsoft_button_text": "",
        "microsoft_allowed_domains": [],
        "microsoft_allowed_tenant_ids": [],
        "microsoft_allow_signup": True,
        # Apple OAuth
        "enable_apple_login": False,
        "apple_client_id": "",
        "apple_team_id": "",
        "apple_key_id": "",
        "apple_private_key": "",
        "apple_button_text": "",
        "apple_allowed_domains": [],
        "apple_allow_signup": True,
    },
    "login_enterprise_sso": {
        "enable_scim": False,
        "scim_bearer_token": "",
        "scim_previous_bearer_token": "",
        "scim_default_role": "user",
        "scim_default_group": "default",
        "scim_link_existing_users_by_email": True,
        "scim_sync_group_memberships": True,
        # SAML defaults
        "enable_saml": False,
        "saml_entity_id": "",
        "saml_sso_url": "",
        "saml_x509_cert": "",
        "saml_advanced_settings": {
            "idp_entity_id": "",
            "additional_x509_certs": [],
            "nameid_format": "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",
            "sign_authn_requests": False,
            "sp_x509_cert": "",
            "sp_private_key": "",
        },
        "saml_button_text": "",
        "saml_allowed_domains": [],
        "saml_enable_jit_provisioning": True,
        "saml_default_role": "user",
        "saml_default_group": "default",
        "saml_attribute_mapping": {},
        "saml_identity_policy": {
            "link_existing_users_by_email": False,
            "sync_profile_on_login": False,
            "sync_email_on_login": False,
            "sync_app_group_on_login": False,
            "sync_role_on_login": False,
            "enable_group_sync": False,
            "group_claim": "groups",
            "groups_separator": ",",
            "required_groups": [],
            "group_to_app_group": [],
            "group_to_role": [],
        },
        # OIDC defaults
        "enable_oidc": False,
        "oidc_client_id": "",
        "oidc_client_secret": "",
        "oidc_discovery_url": "",
        "oidc_issuer": "",
        "oidc_jwks_uri": "",
        "oidc_authorization_endpoint": "",
        "oidc_token_endpoint": "",
        "oidc_userinfo_endpoint": "",
        "oidc_scopes": ["openid", "email", "profile"],
        "oidc_advanced_settings": {
            "token_endpoint_auth_method": "client_secret_basic",
            "prompt": "",
        },
        "oidc_button_text": "",
        "oidc_allowed_domains": [],
        "oidc_enable_jit_provisioning": True,
        "oidc_default_role": "user",
        "oidc_default_group": "default",
        "oidc_attribute_mapping": {},
        "oidc_identity_policy": {
            "link_existing_users_by_email": False,
            "sync_profile_on_login": False,
            "sync_email_on_login": False,
            "sync_app_group_on_login": False,
            "sync_role_on_login": False,
            "enable_group_sync": False,
            "group_claim": "groups",
            "groups_separator": ",",
            "required_groups": [],
            "group_to_app_group": [],
            "group_to_role": [],
        },
    },
    "login_ldap": {
        "enable_ldap": False,
        "ldap_enable_group_sync": False,
        "ldap_label": "Directory Sign-In",
        "ldap_identifier_hint": "Email or directory login",
        "ldap_server_uris": [],
        "ldap_allow_insecure_plaintext_bind": False,
        "ldap_validate_cert": True,
        "ldap_ca_cert_file": "",
        "ldap_connect_timeout_seconds": 10,
        "ldap_receive_timeout_seconds": 10,
        "ldap_bind_dn": "",
        "ldap_bind_password": "",
        "ldap_user_base_dn": "",
        "ldap_user_filter": "(&(objectClass=person)(|(mail={identifier})(uid={identifier})(sAMAccountName={identifier})(userPrincipalName={identifier})))",
        "ldap_user_search_scope": "subtree",
        "ldap_email_attribute": "mail",
        "ldap_first_name_attribute": "givenName",
        "ldap_last_name_attribute": "sn",
        "ldap_display_name_attribute": "displayName",
        "ldap_username_attribute": "uid",
        "ldap_user_id_attribute": "entryUUID",
        "ldap_group_source": "memberOf",
        "ldap_group_attribute": "memberOf",
        "ldap_group_base_dn": "",
        "ldap_group_filter": "(&(objectClass=group)(member={user_dn}))",
        "ldap_group_search_scope": "subtree",
        "ldap_group_name_attribute": "cn",
        "ldap_required_groups": [],
        "ldap_group_to_app_group": [],
        "ldap_group_to_role": [],
        "ldap_enable_jit_provisioning": True,
        "ldap_link_existing_users_by_email": True,
        "ldap_sync_profile_on_login": True,
        "ldap_sync_email_on_login": True,
        "ldap_sync_app_group_on_login": True,
        "ldap_sync_role_on_login": True,
        "ldap_default_role": "user",
        "ldap_default_group": "default",
    },
    "security": {
        "enable_block_user_after_wrong_signin": True,
        "block_user_after_wrong_signin_attempts": 6,
        "block_user_after_wrong_signin_attempts_time_hours": 1,
        "access_token_expire_minutes": 15,
        "refresh_token_expire_minutes": 10080,
        "enable_ip_restrictions": False,
        "check_ip_location_provider": "ipinfo",
        "enable_ip_address_restrictions": False,
        "ip_address_restriction_mode": "blocklist",
        "only_allow_specific_ip": False,
        "allow_specific_ip": [],
        "block_specific_ip": [],
        "enable_ip_country_restrictions": False,
        "ip_country_restriction_mode": "blocklist",
        "only_allow_ip_from_specific_countries": False,
        "allow_country_ip": [],
        "block_country_ip": [],
        "allow_ip_if_no_country_found": False,
        "trust_proxy_headers": False,
        "trusted_proxies": [],
        # Authentication logs cleanup
        "auth_logs_auto_cleanup_enabled": True,
        "auth_logs_cleanup_mode": "age",
        "auth_logs_max_age_days": 90,
        "auth_logs_max_count": 100000,
        "auth_logs_cleanup_interval_seconds": 3600,
        # User delete log retention
        "auth_logs_retention_after_user_delete_mode": "delete_after_days",
        "auth_logs_retention_delete_after_days": 30,
        "audit_logs_retention_after_user_delete_mode": "delete_after_days",
        "audit_logs_retention_delete_after_days": 30,
    },
    "users": {
        "user_deletion_mode": "delete_after_days",
        "user_deletion_retention_days": 30,
        "temporary_account_deletion_mode": "delete_after_days",
        "temporary_account_retention_days": 30,
    },
    "models": {
        "default_model": "",
        "default_pinned_models": [],
    },
    "dictation": {
        "transcription_enabled": False,
        "transcription_provider_id": "",
        "transcription_model": "",
        "live_transcription_enabled": False,
        "live_transcription_provider_id": "",
        "live_transcription_model": "",
        "live_transcription_delay": "low",
        "live_transcription_xai_language": "",
        "live_transcription_xai_endpointing_ms": 10,
        "live_transcription_xai_keyterms": [],
        "live_transcription_xai_filler_words": False,
        "live_transcription_xai_smart_turn": None,
        "live_transcription_xai_smart_turn_timeout_ms": None,
        "live_transcription_xai_vad_threshold": 0.08,
    },
    "read_aloud": {
        "read_aloud_provider_id": "browser_native",
        "read_aloud_model": "",
        "read_aloud_voice": "",
        "read_aloud_response_format": "",
    },
    "realtime": {
        "realtime_enabled": False,
        "realtime_provider_id": "",
        "realtime_model": "",
        "realtime_voice": "alloy",
        "realtime_tools": [],
        "realtime_temperature": None,
        "realtime_max_output_tokens": None,
        "realtime_input_transcription_enabled": True,
        "realtime_output_transcription_enabled": True,
        "realtime_language_code": "",
        "realtime_enable_session_resumption": True,
        "realtime_enable_context_window_compression": True,
        "realtime_compression_trigger_tokens": None,
        "realtime_compression_target_tokens": None,
        "realtime_enable_affective_dialog": False,
        "realtime_enable_proactive_audio": False,
        "realtime_activity_handling": "START_OF_ACTIVITY_INTERRUPTS",
        "realtime_turn_coverage": "TURN_INCLUDES_ONLY_ACTIVITY",
        "realtime_start_sensitivity": "",
        "realtime_end_sensitivity": "",
        "realtime_prefix_padding_ms": 80,
        "realtime_silence_duration_ms": 700,
    },
    "about": {
        "product_key": "",
        "privacy_policy": str(PRIVACY_POLICY_TEMPLATE),
        "privacy_policy_revision": 1,
        "privacy_policy_notice_mode": "none",
        "privacy_policy_notice_message_html": "",
        "privacy_policy_notice_updated_at": "",
        "terms_of_service": str(TERMS_OF_SERVICE_TEMPLATE),
        "terms_of_service_revision": 1,
        "terms_of_service_updated_at": "",
    },
    "api_keys": {
        "ipinfo": "",
        "ipstack": "",
    },
    "slide_presentation": {
        "presentation_model_id": "",
    },
    "code_execution": {
        "max_output_length": 10000,
    },
    "weather_tool": {
        "provider": "open_meteo",
        "geocoding_provider": "open_meteo",
        "openweathermap_api_mode": "free",
        "api_key": "",
    },
    "image_generation": {
        "provider_id": "",
        "model_name": "",
        "settings": {},
    },
    "video_generation": {
        "provider_id": "",
        "model_name": "",
        "duration_seconds": 6,
        "size": "",
        "enable_reference_files": False,
        "timeout_seconds": 600,
        "poll_interval_seconds": 5,
        "max_retries": 2,
    },
    "audio_generation": {
        "provider_id": "",
        "model_name": "",
        "voice": "",
        "response_format": "",
        "language": None,
        "sample_rate": None,
        "bit_rate": None,
        "speed": None,
        "optimize_streaming_latency": None,
        "text_normalization": None,
    },
    "music_generation": {
        "provider_id": "",
        "model_name": "",
        "response_format": "mp3",
        "enable_reference_images": False,
        "max_reference_images": 3,
    },
    "deep_research": {
        "execution_mode": "custom",
        "model_id": "",
        "native_provider_id": "",
        "native_model_name": "deep-research-preview-04-2026",
        "max_revision_rounds": 2,
        "websearch_search_provider": "",
        "websearch_scrape_provider": "",
    },
    "secret": {
        "passkey_padding_secret": "",
        "google_client_id": "",
        "google_client_secret": "",
    },
    "status": {
        "internet_connectivity": True,
        # Persist the last announced version tag to avoid duplicate notifications after restarts
        "latest_version_notified": "",
    },
    "notifications": {  # Admin notifications
        "enable_notifications": False,
        "webhook_url": "",
    },
    "states": {
        "server_setup": False,
    },
    "user_statistics": {
        "enabled": False,
        "regulatory_confirmed": False,
        "tracked_user_ids": [],
        "track_all_users": False,
    },
    "ip_address_statistics": {
        "enabled": False,
        "regulatory_confirmed": False,
        "regulatory_justification": "",
        "policy_reference": "",
        "retention_policy": "Retain IP address security statistics for the configured retention period, then delete.",
        "retention_purpose": "Security monitoring, abuse prevention, blocked-IP analytics, and incident response.",
        "retention_days": 90,
    },
}
