"""Application-level limits for todo payloads and per-user storage."""

MAX_TODO_LISTS_PER_USER = 100
MAX_TODOS_PER_LIST = 1000

MAX_TODO_LIST_DESCRIPTION_LENGTH = 4096
MAX_TODO_CONTENT_LENGTH = 8192
MAX_TODO_NOTES_LENGTH = 16384
MAX_TODO_METADATA_JSON_BYTES = 32768
MAX_TODO_SORT_FIELDS = 10
MAX_TODO_SORT_FIELD_LENGTH = 64
