"""Create the current Omlorix audit schema baseline.

This root revision intentionally replaces every pre-release audit migration.
It builds a fresh database directly from the current SQLAlchemy metadata.

Revision ID: baseline_audit_20260815
Revises:
Create Date: 2026-08-15 20:06:34.234371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.database import AUDIT_DATABASE_SCHEMA


# revision identifiers, used by Alembic.
revision: str = "baseline_audit_20260815"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _audit_schema() -> str:
    """Return the runtime audit schema configured for this migration."""

    return str(op.get_context().version_table_schema or AUDIT_DATABASE_SCHEMA)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auditlogdeletionqueue",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_auditlogdeletionqueue_scheduled_for",
        "auditlogdeletionqueue",
        ["scheduled_for"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_auditlogdeletionqueue_status",
        "auditlogdeletionqueue",
        ["status"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_auditlogdeletionqueue_user_id",
        "auditlogdeletionqueue",
        ["user_id"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_table(
        "authenticationlogs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("auth_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_info", sa.String(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("flow", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", "timestamp"),
        schema=_audit_schema(),
        postgresql_partition_by="RANGE (timestamp)",
    )
    op.create_index(
        "ix_authenticationlogs_timestamp",
        "authenticationlogs",
        ["timestamp"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_authenticationlogs_correlation_id",
        "authenticationlogs",
        ["correlation_id"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_authenticationlogs_error_code",
        "authenticationlogs",
        ["error_code"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_authenticationlogs_user_id",
        "authenticationlogs",
        ["user_id"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_table(
        "authlogdeletionqueue",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_authlogdeletionqueue_scheduled_for",
        "authlogdeletionqueue",
        ["scheduled_for"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_authlogdeletionqueue_status",
        "authlogdeletionqueue",
        ["status"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_authlogdeletionqueue_user_id",
        "authlogdeletionqueue",
        ["user_id"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_table(
        "logs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column(
            "share_refs_scrubbed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", "timestamp"),
        schema=_audit_schema(),
        postgresql_partition_by="RANGE (timestamp)",
    )
    op.create_index(
        "ix_logs_action", "logs", ["action"], unique=False, schema=_audit_schema()
    )
    op.create_index(
        "ix_logs_action_timestamp_id",
        "logs",
        ["action", "timestamp", "id"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_logs_category_timestamp_id",
        "logs",
        ["category", "timestamp", "id"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_logs_share_refs_scrubbed",
        "logs",
        ["share_refs_scrubbed"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_logs_timestamp", "logs", ["timestamp"], unique=False, schema=_audit_schema()
    )
    op.create_index(
        "ix_logs_timestamp_id",
        "logs",
        ["timestamp", "id"],
        unique=False,
        schema=_audit_schema(),
    )
    op.create_index(
        "ix_logs_user_id", "logs", ["user_id"], unique=False, schema=_audit_schema()
    )
    op.create_index(
        "ix_logs_user_timestamp_id",
        "logs",
        ["user_id", "timestamp", "id"],
        unique=False,
        schema=_audit_schema(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_logs_user_timestamp_id", table_name="logs", schema=_audit_schema()
    )
    op.drop_index("ix_logs_user_id", table_name="logs", schema=_audit_schema())
    op.drop_index("ix_logs_timestamp_id", table_name="logs", schema=_audit_schema())
    op.drop_index("ix_logs_timestamp", table_name="logs", schema=_audit_schema())
    op.drop_index(
        "ix_logs_share_refs_scrubbed", table_name="logs", schema=_audit_schema()
    )
    op.drop_index("ix_logs_action", table_name="logs", schema=_audit_schema())
    op.drop_index(
        "ix_logs_category_timestamp_id", table_name="logs", schema=_audit_schema()
    )
    op.drop_index(
        "ix_logs_action_timestamp_id", table_name="logs", schema=_audit_schema()
    )
    op.drop_table("logs", schema=_audit_schema())
    op.drop_index(
        "ix_authlogdeletionqueue_user_id",
        table_name="authlogdeletionqueue",
        schema=_audit_schema(),
    )
    op.drop_index(
        "ix_authlogdeletionqueue_status",
        table_name="authlogdeletionqueue",
        schema=_audit_schema(),
    )
    op.drop_index(
        "ix_authlogdeletionqueue_scheduled_for",
        table_name="authlogdeletionqueue",
        schema=_audit_schema(),
    )
    op.drop_table("authlogdeletionqueue", schema=_audit_schema())
    op.drop_index(
        "ix_authenticationlogs_user_id",
        table_name="authenticationlogs",
        schema=_audit_schema(),
    )
    op.drop_index(
        "ix_authenticationlogs_timestamp",
        table_name="authenticationlogs",
        schema=_audit_schema(),
    )
    op.drop_table("authenticationlogs", schema=_audit_schema())
    op.drop_index(
        "ix_auditlogdeletionqueue_user_id",
        table_name="auditlogdeletionqueue",
        schema=_audit_schema(),
    )
    op.drop_index(
        "ix_auditlogdeletionqueue_status",
        table_name="auditlogdeletionqueue",
        schema=_audit_schema(),
    )
    op.drop_index(
        "ix_auditlogdeletionqueue_scheduled_for",
        table_name="auditlogdeletionqueue",
        schema=_audit_schema(),
    )
    op.drop_table("auditlogdeletionqueue", schema=_audit_schema())
    # ### end Alembic commands ###
