{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omlorix.fullname" . }}-env
  labels:
    {{- include "omlorix.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
